### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Clozee
email: ajuda@clozee.com.br
description: Expresse sua moda e inspire-se.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.clozee.com.br" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: "#efeeff"
twitter_username: clozee.app
github_username: clozee.app
author: Clozee
logo: assets/images/large-logo.png
twitter:
  username: clozee.app
social:
  name: Clozee
  links:
    - https://twitter.com/clozee.app
    - https://www.facebook.com/clozee.app
    - https://www.linkedin.com/in/clozee.app
    - https://www.instagram.com/clozee.app

languages: ["pt-BR"]
ampdir: amp

# github: https://github.com/sandoche/Mobile-app-landingpage-template

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
