name: Clozee
description: Uma nova forma de se relacionar com o seu guarda-roupas.
full_description: '- Busca inspirações e encontra looks incríveis<br>
<br>- Faz uma grana extra com aquela peça que está parada no seu guarda-roupas<br>
<br>- Pode comprar com a segurança e praticidade de receber em casa. Tudo que é postado na Clozee está à venda!'
android: https://play.google.com/store/apps/details?id=br.com.clozee
iOS: https://telegra.ph/Replace-this-link-07-23
web: false
screenshots:
  - A.png
  - B.png
  - C.png
  - D.png

